src/Pro3x/InvoiceBundle/Entity/Invoice.php
<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Invoice
 *
 * @ORM\Table(name="pro3x_invoices")
 * @ORM\Entity(repositoryClass="Pro3x\InvoiceBundle\Entity\InvoiceRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Invoice
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
	
	/**
	 * @OneToMany(targetEntity="InvoiceItem", mappedBy="invoice", cascade={"all"})
	  */
	private $items;

	/**
	 * @ManyToOne(targetEntity="Customer", inversedBy="invoices")
	  */
	private $customer;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $status;
	
	/**
	 * @ManyToOne(targetEntity="Pro3x\SecurityBundle\Entity\User", inversedBy="invoices")
	  */
	private $user;
		
	/**
	 * @var Position Point of Sale position at location
	 * @ManyToOne(targetEntity="Position", inversedBy="invoices")
	  */
	private $position;
	
	/**
	 * @ORM\Column(type="datetime")
	 */
	private $created;
	
	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 */
	private $tenderDate;
	
	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $sequence;
	
	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $tenderSequence;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $uuid;

	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $companyTaxNumber;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $uniqueInvoiceNumber;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $originalInvoiceNumber;
	
	/**
	 * @ManyToOne(targetEntity="Template", inversedBy="invoices")
	  */
	private $template;
	
	/**
	 * @ManyToOne(targetEntity="Template", inversedBy="tenders")
	  */
	private $tenderTemplate;
	
	/**
	 * @ORM\Column(type="decimal", scale=2)
	 */
	private $invoiceTotal;

	/**
	 * @ManyToOne(targetEntity="DailySalesReport", inversedBy="invoices")
	  */
	private $dailyReport;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $companySecureCode;
        
        /**
         *
         * @ORM\Column(type="text", nullable=true)
         */
        private $note;
        
        function getNote() {
            return $this->note;
        }

        function setNote($note) {
            $this->note = $note;
            return $this;
        }
	
	public function getCompanySecureCode()
	{
		return $this->companySecureCode;
	}
	
	public function getOriginalInvoiceNumber()
	{
		return $this->originalInvoiceNumber;
	}

	public function setOriginalInvoiceNumber($originalInvoiceNumber)
	{
		$this->originalInvoiceNumber = $originalInvoiceNumber;
	}

	public function setCompanySecureCode($companySecureCode)
	{
		$this->companySecureCode = $companySecureCode;
	}

	public function getTenderTemplate()
	{
		return $this->tenderTemplate;
	}

	public function setTenderTemplate($tenderTemplate)
	{
		$this->tenderTemplate = $tenderTemplate;
	}

	public function getDailyReport()
	{
		return $this->dailyReport;
	}

	public function setDailyReport($report)
	{
		$this->dailyReport = $report;
	}

	private $numeric;
	
	public function getTenderSequence()
	{
		return $this->tenderSequence;
	}

	public function setTenderSequence($tenderSequence)
	{
		$this->tenderSequence = $tenderSequence;
	}

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $isFiscalTransaction;

	public function __construct()
	{
		$this->created = new \DateTime('now');
		
		$this->sequence = null;
		$this->invoiceTotal = 0;
		$this->items = new ArrayCollection();
		$this->locked = false;
		
		$this->isFiscalTransaction = false;
	}
	
	public function hasCustomerMessage()
	{
		if($this->getCustomer() != null && $this->getCustomer()->getMessage() != '')
		{
			return true;
		}
		
		return false;
	}
	
	public function hasCustomerWarning()
	{
		if($this->getCustomer() != null && $this->getCustomer()->getWarning() != '')
			return true;
		else
			return false;
	}
	
	public function getTenderDate()
	{
		return $this->tenderDate;
	}

	public function setTenderDate($tenderDate)
	{
		$this->tenderDate = $tenderDate;
	}

	public function isFiscalTransaction()
	{
		return $this->isFiscalTransaction;
	}

	public function setFiscalTransaction($isFiscalTransaction)
	{
		$this->isFiscalTransaction = $isFiscalTransaction;
	}

	public function isInvalid()
	{
		if($this->getSequence() != null && $this->isFiscalTransaction() == true && $this->getUniqueInvoiceNumber() == null)
			return true;
		else
			return false;
	}
	
	public function getInvoiceTotal()
	{
		return $this->invoiceTotal;
	}

	public function setInvoiceTotal($invoiceTotal)
	{
		$this->invoiceTotal = $invoiceTotal;
	}
	
	public function calculate()
	{
		$this->setInvoiceTotal($this->getTotal());
	}

	/**
	 * 
	 * @return Template
	 */
	public function getTemplate()
	{
		return $this->template;
	}

	public function setTemplate($template)
	{
		$this->template = $template;
	}

	public function getUniqueInvoiceNumber()
	{
		return $this->uniqueInvoiceNumber;
	}
	
	public function getUniqueInvoiceNumberFormated()
	{
		if($this->uniqueInvoiceNumber)
			return $this->uniqueInvoiceNumber;
		else
			return 'Nedostupan';
	}

	public function setUniqueInvoiceNumber($uniqueInvoiceNumber)
	{
		$this->uniqueInvoiceNumber = $uniqueInvoiceNumber;
	}

	public function getCompanyTaxNumber()
	{
		return $this->companyTaxNumber;
	}

	public function setCompanyTaxNumber($companyTaxNumber)
	{
		$this->companyTaxNumber = $companyTaxNumber;
	}

	public function getSequence()
	{
		return $this->sequence;
	}

	public function setSequence($sequence)
	{
		$this->sequence = $sequence;
	}
	
	public function getCreated()
	{
		return $this->created;
	}

	public function setCreated($created)
	{
		$this->created = $created;
	}

	public function getUuid()
	{
		return $this->uuid;
	}

	public function setUuid($uuid)
	{
		$this->uuid = $uuid;
	}

	public function getSequenceFormated()
	{
		if($this->getSequence() == null)
		{
			if($this->getTenderSequence() == null)
			{
				return 'skica';
			}
			else
			{
				return 'ponuda | ' . $this->getTenderSequence();
			}
		}
		else
		{
			return $this->getSequence();
		}
	}
	
	public function getDateTimeFormated()
	{
		return $this->created->format('d.m.Y H:i\h');
	}

	public function getDateFormated()
	{
		return $this->created->format('d.m.Y');
	}
	
	public function getTimeFormated()
	{
		return $this->created->format('H:i');
	}

	public function getPosition()
	{
		return $this->position;
	}

	/**
	 * 
	 * @param Position $position
	 */
	public function setPosition($position)
	{
		$this->position = $position;
		
		$this->setCompanyTaxNumber($position->getLocation()->getCompanyTaxNumber());
	}

	/**
	 * 
	 * @return \Pro3x\SecurityBundle\Entity\User
	 */
	public function getUser()
	{
		return $this->user;
	}

	public function setUser($user)
	{
		$this->user = $user;
	}
	
	public function getUserDisplayName()
	{
		return $this->getUser()->getDisplayName();
	}

	/**
	 * 
	 * @return \Pro3x\Online\Numeric
	 */
	public function getNumeric()
	{
		return $this->numeric;
	}

	public function setNumeric($numeric)
	{
		$this->numeric = $numeric;
	}

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
	
	/**
	 * 
	 * @return \Doctrine\Common\Collections\ArrayCollection
	 */
	public function getItems()
	{
		if($this->getNumeric())
		{
			foreach ($this->items as $item) /* @var $item InvoiceItem */
			{
				$item->setNumeric($this->getNumeric());
			}
		}
		
		return $this->items;
	}

	public function setItems($items)
	{
		$this->items = $items;
	}

	/**
	 * 
	 * @return Customer
	 */
	public function getCustomer()
	{
		return $this->customer;
	}

	public function setCustomer($customer)
	{
		$this->customer = $customer;
	}

	public function getStatus()
	{
		return $this->status;
	}

	public function setStatus($status)
	{
		$this->status = $status;
	}
	
	private function getTaxItemsArray()
	{
		$taxes = array();
		
		foreach ($this->getItems() as $item) /* @var $item InvoiceItem */
		{
			foreach ($item->getTaxes() as $tax) /* @var $tax InvoiceItemTax */
			{
				$taxes[$tax->getTaxId()][] = $tax;
			}
		}
		
		return $taxes;
	}
	
	public function getTaxItems()
	{
		$taxes = $this->getTaxItemsArray();
		$aggTax = array();
		
		foreach($taxes as $key => $taxItems) /* @var $taxItems InvoiceItemTax[] */
		{
			$item = array();
			$item['base'] = 0;
			$item['amount'] = 0;
			$item['rate'] = $taxItems[0]->getTaxRate();
			$item['description'] = $taxItems[0]->getTaxDescription();
			$item['total'] = 0;
			$item['group'] = $taxItems[0]->getTaxGroup();
			
			foreach ($taxItems as $taxItem) /* @var $taxItem InvoiceItemTax */
			{
				$item['base'] += $taxItem->getItem()->getTotalPrice();
				$item['amount'] += $taxItem->getTaxAmount();
				$item['total'] = $item['base'] + $item['amount'];
			}
			
			$aggTax[] = $item;
		}
		
		$nf = $this->getNumeric()->getNumberFormatter();
		foreach ($aggTax as &$item)
		{
			$item['baseNumeric'] = $item['base'];
			$item['base'] = $nf->format($item['base']);
			
			$item['totalNumeric'] = $item['total'];
			$item['total'] = $nf->format($item['total']);
			
			$item['amountNumeric'] = $item['amount'];
			$item['amount'] = $nf->format($item['amount']);
			
			$item['rateNumeric'] = $item['rate'] * 100;
			$item['rate'] = $nf->format($item['rate'] * 100);
		}
		
		return $aggTax;
	}
	
	public function getTotal()
	{
		$total = 0;
		
		foreach ($this->getItems() as $item) /* @var $item InvoiceItem */
		{
			$total += $item->getDicountPrice();
		}

		return $total;
	}
	
	public function getTotalFormated()
	{
		return $this->getNumeric()->getNumberFormatter()->format($this->getTotal());
	}

	public function getFiscalTotalFormated()
	{

src/Pro3x/InvoiceBundle/Entity/Product.php
<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\ManyToOne;

/**
 * Product
 *
 * @ORM\Table(name="pro3x_products")
 * @ORM\Entity(repositoryClass="Pro3x\InvoiceBundle\Entity\ProductRepository")
 */
class Product
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $name;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $barcode;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $code;
	
	/**
	 * @ORM\Column(type="decimal", precision=14, scale=6)
	 */
	private $unitPrice;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $unit;
	
	/**
	 * @ORM\Column(type="decimal", precision=14, scale=6)
	 */
	private $inputPrice;
	
	/**
	 * @ORM\Column(type="decimal", precision=14, scale=2)
	 */
	private $taxedInputPrice;
	
	/**
	 * @OneToMany(targetEntity="\Pro3x\WarehouseBundle\Entity\ReceiptItem", mappedBy="product")
	  */
	private $receiptItems;

	/**
	 * @OneToMany(targetEntity="\Pro3x\RegistrationKeysBundle\Entity\RegistrationKey", mappedBy="product")
	  */
	private $registrationKeys;
	
	private $numeric;
	
	public function getInputPrice()
	{
		return $this->inputPrice;
	}

	public function setInputPrice($inputPrice)
	{
		$this->inputPrice = $inputPrice;
	}

	public function getTaxedInputPrice()
	{
		return $this->taxedInputPrice;
	}

	public function setTaxedInputPrice($taxedInputPrice)
	{
		$this->taxedInputPrice = $taxedInputPrice;
	}

	/**
	 * 
	 * @return \Pro3x\Online\Numeric
	 */
	public function getNumeric()
	{
		return $this->numeric;
	}

	public function setNumeric($numeric)
	{
		$this->numeric = $numeric;
	}

	/**
	 *
	 * @var ArrayCollection
	 * @ORM\ManyToMany(targetEntity="TaxRate", inversedBy="products")
	 * @ORM\JoinTable(name="pro3x_product_tax_rates")
	 */
	private $taxRates;
	
	/**
	 * @ManyToOne(targetEntity="TaxRate", inversedBy="inputProducts")
	  */
	private $inputTaxRate;
	
	/**
	 * 
	 * @return TaxRate
	 */
	public function getInputTaxRate()
	{
		return $this->inputTaxRate;
	}

	public function setInputTaxRate($inputTaxRate)
	{
		$this->inputTaxRate = $inputTaxRate;
	}

	function __construct()
	{
		$this->unitPrice = 0;
		$this->taxRates = new ArrayCollection();
		$this->unit = "kom";
		
		$this->inputPrice = 0;
		$this->taxedInputPrice = 0;
		$this->inputTaxRate = null;
	}

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
	
	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
		return $this;
	}

	public function getBarcode()
	{
		return $this->barcode;
	}

	public function setBarcode($barcode)
	{
		$this->barcode = $barcode;
		return $this;
	}

	public function getCode()
	{
		return $this->code;
	}

	public function setCode($code)
	{
		$this->code = $code;
		return $this;
	}

	public function getUnitPrice()
	{
		return $this->getTaxedPrice() / (1 + $this->getTotalTaxRate());
	}
	
	public function getUnitPriceFormated()
	{
		return $this->getNumeric()->getNumberFormatter(2)->format($this->getUnitPrice());
	}

	public function setUnitPrice($unitPrice)
	{
		$this->unitPrice = $unitPrice;
		return $this;
	}
	
	public function getTaxAmountFormated()
	{
		return $this->getNumeric()->getNumberFormatter(2)->format($this->getTaxAmount());
	}
	
	public function getTaxAmount()
	{
		return $this->getTaxedPrice() - $this->getUnitPrice();
	}
	
	public function getTaxedPriceFormated()
	{
		return $this->getNumeric()->getNumberFormatter(2)->format($this->getTaxedPrice());
	}
	
	public function getTotalTaxRate()
	{
		$totalRate = 0;
		
		foreach ($this->getTaxRates() as $tax) /* @var $tax TaxRate */
		{
			$totalRate += $tax->getRate();
		}
		
		return $totalRate;
	}
	
	public function getTaxedPrice()
	{
		
		return round($this->unitPrice * (1 + $this->getTotalTaxRate()), 2);
	}

	public function getUnit()
	{
		return $this->unit;
	}

	public function setUnit($unit)
	{
		$this->unit = $unit;
		return $this;
	}

	public function getTaxRates()
	{
		return $this->taxRates;
	}

	public function setTaxRates($taxRates)
	{
		$this->taxRates = $taxRates;
		return $this;
	}

}

src/Pro3x/InvoiceBundle/Resources/views/Invoice/add-item-mobile.html.twig
<div class="panel panel-default item-{{ item.id }}">
    <div class="panel-heading">
        <h3 class="panel-title">{{ item.description }}</h3>
    </div>
    
    <table class="table">
        <tr>
            <td class="active" style="width: 40%;">Cijena</td>
            <td>{{ item.taxedPriceFormated }}</td>
        </tr>
        <tr>
            <td class="active" style="width: 40%;">Količina</td>
            <td>{{ item.amountFormated }} <span class="pro3x_unit">{{ item.unit }}</td>
        </tr>
        <tr>
            <td class="active" style="width: 40%;">Osnovica</td>
            <td>{{ item.totalTaxedPriceFormated }}</td>
        </tr>
        <tr>
            <td class="active" style="width: 40%;">Popust</td>
            <td>{{ item.discountFormated }} %</td>
        </tr>
        <tr>
            <td class="active" style="width: 40%;">Ukupno</td>
            <td>{{ item.discountPriceFormated }}</td>
        </tr>
    </table>
        
    <div class="panel-footer pro3x-document-action">
        <a data-target=".item-{{ item.id }}" class="btn btn-primary pro3x_delete_invoice_item" href="{{ path('delete_invoice_item', {'id' : item.id}) }}">{{ 'Izbriši stavku'|trans }}</a>
    </div>
</div>

{#<tr data-total="{{ item.taxedPrice }}">
    <td>{{ item.description }}{% if item.invoice.sequence == null and item.invoice.tenderSequence == null %} <a class="pro3x_delete_invoice_item" href="{{ path('delete_invoice_item', {'id' : item.id}) }}">{{ 'izbriši'|trans }}</a>{% endif %}</td>
    <td style="text-align: right;">{{ item.taxedPriceFormated }}</td>
    <td style="text-align: right;"></span></td>
    <td style="text-align: right;"></td>
    <td style="text-align: right;">%</td>
    <td style="text-align: right;"></td>
</tr>#}

src/Pro3x/InvoiceBundle/Resources/views/Invoice/addItem.html.twig
<tr data-total="{{ item.taxedPrice }}" class="item-{{ item.id}}" data-id="{{ item.id }}">
    <td>
        {% if item.invoice.sequence == null and item.invoice.tenderSequence == null %} <a data-target=".item-{{ item.id }}" class="pro3x_delete_invoice_item pro3x-document-action" href="{{ path('delete_invoice_item', {'id' : item.id}) }}"><span class="glyphicon glyphicon-remove"></span></a>{% endif %}
        <div class="invoice-item-description" data-id="{{ item.id }}">{{ item.description|raw }}</div>
    </td>
    <td style="text-align: right;">{{ item.taxedPriceFormated }}</td>
    <td style="text-align: right;">{{ item.amountFormated }} <span class="pro3x_unit">{{ item.unit }}</span></td>
    <td style="text-align: right;">{{ item.totalTaxedPriceFormated }}</td>
    <td style="text-align: right;">{{ item.discountFormated }}%</td>
    <td style="text-align: right;">{{ item.discountPriceFormated }}</td>
</tr>

src/Pro3x/InvoiceBundle/Resources/views/Invoice/customerColumn.html.twig
{% if item.customer %}
    <div>{{ item.customer.name }}</div>
    <div>{{ item.customer.addressDescription|join(', ') }}</div>
{% endif %}

src/Pro3x/InvoiceBundle/Resources/views/Invoice/idColumn.html.twig
{%if item.dailyReport is null %} + {% endif %}<span{% if item.isInvalid %} style="color: red"{% endif %}>{{ item.sequenceFormated }}</span>
    
    

src/Pro3x/InvoiceBundle/Resources/views/Invoice/infoColumn.html.twig
<div>{{ item.dateTimeFormated }}, {{ item.user.displayName }}</div>
<div>{{ item.position.location.name }}, {{ item.position.name }}</div>

src/Pro3x/InvoiceBundle/Resources/views/Invoice/invoice-info.html.twig
<div id="pro3x-invoice-info">
    {% if invoice.customer or invoice.originalInvoiceNumber or invoice.note %}
    <div class="col-md-12" style="padding-top: 5px;">

        <div class="panel panel-default">

            <table class="table table-bordered">
                {% if invoice.customer %}
                <tr>
                    <th style="width: 350px">Kupac</th>
                    <td>
                        <a class="pull-right" title="Kartica" style="margin-right: 8px;" target="_blank" href="{{ path('customer_history', {'customer': invoice.customer.id}) }}">
                            <span class="glyphicon glyphicon-folder-open"></span>
                        </a>
                        <a href="{{ path('edit_client', {'id': invoice.customer.id, 'back': app.request.uri}) }}">{{ invoice.customer.name }}</a> 
                    </td>
                </tr>
                {% endif %}

                {% if invoice.originalInvoiceNumber %}
                <tr>
                    <th style="width: 350px">Broj računa</th>
                    <td>{{ invoice.originalInvoiceNumber }}</td>
                </tr>
                {% endif %}
                
                {% if invoice.note %}
                <tr>
                    <th style="width: 350px">Napomena</th>
                    <td>{{ invoice.note|raw }}</td>
                </tr>
                {% endif %}

            </table>
        </div>
    </div>
    {% endif %}
</div>

src/Pro3x/InvoiceBundle/Resources/views/Invoice/invoice-title-mobile.html.twig
<span class="pro3x-invoice-title-mobile">{% if invoice.sequence is null  %}{{ 'Novi račun'|trans }}{% else %}{{ 'Račun'|trans|title }}{% endif %}</span>

src/Pro3x/InvoiceBundle/Resources/views/Invoice/print-qr-invoice-template.html.twig
<div class="pro3x-document report"></div>

<div class="pro3x-document report-template">

    <div class="report-page-header">
        <div style="padding-top: 10mm; padding-left: 10mm;">
            {% if invoice.position.location.logo %}
                <img src="{{ invoice.position.location.logo }}" />
            {% endif %}
        </div>

        <div style="text-align: right; font-size: 12px; font-weight: 300; padding-right: 10mm;">
            <div>{{ invoice.position.location.companyName }}</div>
            <div>{{ invoice.position.location.address }}</div>
            <div>{{ invoice.position.location.other }}</div>
        </div>

        <div class="clearfix"></div>

        <h1 class="pro3x"><span class="pro3x-report-title">{{ invoice.template.description|upper }}</span><small class="pro3x-report-subtitle"><span class="report-page-number"></span> / <span class="report-page-count"></span></small></h1>
        <div class="clearfix"></div>


        <div style="background-color: {{ background }} !important; padding: 4.5mm 5mm; width: 200mm; margin-left: 5mm;">
            <div style="width: 85mm; float: left;">
                <div><span class="pro3x-name">Oznaka</span>{{ invoice.sequence }} - {{ invoice.position.location.name }} - {{ (invoice.position.name)?invoice.position.name:invoice.position.id }}</div>
                <div><span class="pro3x-name">Datum</span>{{ invoice.dateFormated }}</div>
                <div><span class="pro3x-name">Vrijeme</span>{{ invoice.timeFormated }}h</div>

                {% if invoice.template.dueDays %}
                    <div><span class="pro3x-name">Rok plaćanja</span>{{ invoice.created|date_modify(invoice.template.dueDays)|date('d.m.Y') }}</div>
                {% else %}
                    <div><span class="pro3x-name">Ukupno</span>{{ invoice.totalFormated }}kn</div>
                {% endif %}
            </div>

            {% if invoice.customer %}    
                <div style="float: right; width: 100mm;">
                    <div class="pro3x-value"><span class="pro3x-name">Kupac</span>{{ invoice.customer.name }}</div>
                    <div class="pro3x-value"><span class="pro3x-name">Adresa</span>{{ invoice.customer.address }}</div>
                    <div class="pro3x-value"><span class="pro3x-name">Lokacija</span>{{ invoice.customer.location }}</div>
                    <div class="pro3x-value"><span class="pro3x-name">OIB</span>{% if invoice.customer.taxNumber %}{{ invoice.customer.taxNumber }}{% endif %}</div>
                </div>
            {% endif %}  

            <div class="clearfix"></div>
        </div>
    </div>
        
    <div class="report-content">
        <div class="panel panel-default" style="width: 200mm; margin: 5mm 5mm 5mm 5mm;">
        <table class="table">
            <thead>
                <tr>
                    <th>Naziv</th>
                    <th style="text-align: right;">Cijena</th>
                    <th style="text-align: right;">Količina</th>
                    <th style="text-align: right;">Osnovica</th>
                    <th style="text-align: right;">Popust</th>
                    <th style="text-align: right;">Ukupno</th>
                </tr>
            </thead>
            <tbody>
            {% for  item in invoice.items %}
                    <tr class="report-item">
                        <td>
                            <span class="pro3x-index pull-left">{{ loop.index }}.</span>
                            <div style="margin-left: 7mm;">{{ item.description|raw }}</div>
                        </td>
                        <td style="text-align: right;">{{ item.taxedPriceFormated }}</td>
                        <td style="text-align: right;"> {{ item.amount }}<span style="display: inline-block; width: 10mm; text-align: right;">{{ item.unit }}</span></td>
                        <td style="text-align: right;">{{ item.totalTaxedPriceFormated }}</td>
                        <td style="text-align: right;">{{ item.discountFormated }} %</td>
                        <td style="text-align: right;">{{ item.discountPriceFormated }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
        <div class="clearfix"></div>
    </div>
            
    <div class="report-content-footer">
        <div style="text-align: right; margin-top: 0mm;">
            <h3 style="margin: 0mm 10mm 0mm 0mm; font-weight: 300;">Ukupno: {{ invoice.totalFormated }}kn</h3>
        </div>

        <div style="clear: both;"></div>

        {% if invoice.taxItems %}
        <table class="pro3x">
            <thead>
                <tr>
                    <th style="padding-left: 0mm;">Porez</th>
                    <th style="text-align: right;">Stopa</th>
                    <th style="text-align: right;">Osnovica</th>
                    <th style="text-align: right;">Iznos</th>
                </tr>
            </thead>
            <tbody>
            {% for  item in invoice.taxItems %}
                    <tr>
                        <td style="padding-left: 0;">
                            <span style="display: inline-block; width: 5mm; text-align: right; margin-right: 5mm;">{{ loop.index }}.</span>{{ item.description }}
                        </td>
                        <td style="text-align: right;">{{ item.rate }} %</td>
                        <td style="text-align: right;">{{ item.base }}</td>
                        <td style="text-align: right;">{{ item.amount }}</td>
                    </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}

        <div style="margin-top: 5mm; margin-left: 10mm;">
            <div>Način plaćanja: {{invoice.template.paymentMethod}}</div>
            <div>Operater:  {{ invoice.user.displayName }}</div>
        </div>

        <div style="margin-top: 5mm; margin-left: 10mm;">
            {% if invoice.companySecureCode %}
                {% if invoice.originalInvoiceNumber %}
                    <div style="margin-bottom: 5mm;">BR: {{ invoice.originalInvoiceNumber }}</div>
                {% endif %}

                <div>JIR: {{ invoice.uniqueInvoiceNumber?invoice.uniqueInvoiceNumber:'Trenutno nedostupan' }}</div>
                <div>ZKI: {{ invoice.companySecureCode }}</div>
            {% endif %}
        </div>
        
        {% if invoice.note %}
        <div style="margin-top: 5mm; margin-left: 10mm;">
            {{ invoice.note|raw }}
        </div>    
        {% endif %}

        <div id="qrcode" data-code="https://porezna.gov.hr/rn/?zki={{invoice.companySecureCode}}&datv={{ invoice.fiscalDateTimeFormated }}&izn={{ invoice.fiscalTotalFormated }}">

        </div>
    </div>
        
    <div class="pro3x-footer report-page-footer" style="background-color: {{ background }} !important;">
        <div>{{ invoice.position.location.note1 }}</div>
        <div>{{ invoice.position.location.note2 }}</div>
    </div>
</div>