src/Pro3x/InvoiceBundle/Entity/Customer.php
<?php

namespace Pro3x\InvoiceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Pro3x\WarehouseBundle\Entity\Receipt;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Client
 *
 * @ORM\Table(name="pro3x_clients")
 * @ORM\Entity(repositoryClass="Pro3x\InvoiceBundle\Entity\CustomerRepository")
 * @InheritanceType("SINGLE_TABLE")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"customer" = "Customer", "supplier" = "\Pro3x\WarehouseBundle\Entity\Supplier"})
 */
class Customer
{
	/**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
	
	/**
	 * @ORM\Column(type="string")
	 */
	private $name;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $address;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $location;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $taxNumber;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $phone;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $cellPhone;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $email;
	
	/**
	 * @OneToMany(targetEntity="Invoice", mappedBy="customer")
	  */
	private $invoices;
	
	/**
	 * @OneToMany(targetEntity="\Pro3x\RegistrationKeysBundle\Entity\RegistrationKey", mappedBy="customer")
	  */
	private $registrationKeys;
	
	/**
	 * @OneToMany(targetEntity="\Pro3x\WarehouseBundle\Entity\Receipt", mappedBy="supplier")
	  */
	private $receipts;
	
	/**
	 * @OneToMany(targetEntity="CustomerRelation", mappedBy="owner")
	  */
	private $relations;
	
	/**
	 * @OneToMany(targetEntity="Note", mappedBy="customer")
	  */
	private $notes;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $accomodation;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $otherAccomodation;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $ownership;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $otherOwnership;
	
	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	private $message;
	
	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	private $warning;
	
	/**
	 * @ORM\Column(type="datetime", nullable=true)
	 */
	private $birthday = null;
	
	/**
	 * @Assert\File(maxSize="6000000")
	 * @var type 
	 */
	private $file;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	private $image;
	
	/**
	 * 
	 * @return \Symfony\Component\HttpFoundation\File\UploadedFile
	 */
	public function getFile()
	{
		return $this->file;
	}

	public function setFile($file)
	{
		$this->file = $file;
	}

	public function getImage()
	{
		return $this->image;
	}

	public function setImage($image)
	{
		$this->image = $image;
	}

	public function getBirthday()
	{
		return $this->birthday;
	}

	public function setBirthday($birthday)
	{
		$this->birthday = $birthday;
	}

	public function getOtherAccomodation()
	{
		return $this->otherAccomodation;
	}

	public function setOtherAccomodation($otherAccomodation)
	{
		$this->otherAccomodation = $otherAccomodation;
	}

	public function getOtherOwnership()
	{
		return $this->otherOwnership;
	}

	public function setOtherOwnership($otherOwnership)
	{
		$this->otherOwnership = $otherOwnership;
	}

	public function getMessage()
	{
		return $this->message;
	}

	public function setMessage($message)
	{
		$this->message = $message;
	}

	public function getWarning()
	{
		return $this->warning;
	}

	public function setWarning($warning)
	{
		$this->warning = $warning;
	}

	public function getAccomodation()
	{
		return $this->accomodation;
	}

	public function setAccomodation($accomodation)
	{
		$this->accomodation = $accomodation;
	}

	public function getOwnership()
	{
		return $this->ownership;
	}

	public function setOwnership($ownership)
	{
		$this->ownership = $ownership;
	}

	public function getRegistrationKeys()
	{
		return $this->registrationKeys;
	}

	public function getReceipts()
	{
		return $this->receipts;
	}

	public function getNotes()
	{
		return $this->notes;
	}

	public function getRelations()
	{
		return $this->relations;
	}

	public function getInvoices()
	{
		return $this->invoices;
	}

	public function setInvoices($invoices)
	{
		$this->invoices = $invoices;
	}

	public function getName()
	{
		return $this->name;
	}

	public function setName($name)
	{
		$this->name = $name;
	}

	public function getAddress()
	{
		return $this->address;
	}

	public function setAddress($address)
	{
		$this->address = $address;
	}

	public function getLocation()
	{
		return $this->location;
	}

	public function setLocation($location)
	{
		$this->location = $location;
	}

	public function getTaxNumber()
	{
		return $this->taxNumber;
	}

	public function setTaxNumber($taxNumber)
	{
		$this->taxNumber = $taxNumber;
	}

	public function getPhone()
	{
		return $this->phone;
	}

	public function setPhone($phone)
	{
		$this->phone = $phone;
	}

	public function getCellPhone()
	{
		return $this->cellPhone;
	}

	public function setCellPhone($cellPhone)
	{
		$this->cellPhone = $cellPhone;
	}
	
	public function getPhones()
	{
		$phones = array();
		
		if($this->getPhone()) $phones[] = $this->getPhone ();
		if($this->getCellPhone()) $phones[] = $this->getCellPhone ();
		
		return $phones;
	}
	
	public function getDescription()
	{
		$description = array();
		$description[] = $this->getName();
		
		if($this->getAddress()) $description[] = $this->getAddress ();
		if($this->getLocation()) $description[] = $this->getLocation ();

		return $description;
	}
	
	public function getDescriptionFormated()
	{
		return implode(", ", $this->getDescription());
	}
	
	public function getAddressDescription()
	{
		$description = array();
		
		if($this->getAddress()) $description[] = $this->getAddress ();
		if($this->getLocation()) $description[] = $this->getLocation ();
		
		return $description;
	}

	public function getEmail()
	{
		return $this->email;
	}

	public function setEmail($email)
	{
		$this->email = $email;
	}

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
}

src/Pro3x/InvoiceBundle/Controller/CustomerController.php
<?php

namespace Pro3x\InvoiceBundle\Controller;

use Pro3x\AppBundle\Controller\AdminController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Pro3x\InvoiceBundle\Form\CustomerType;
use Pro3x\InvoiceBundle\Entity\Customer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/admin/customers")
 */
class CustomerController extends AdminController
{
	/**
	 * @Route("/add", name="add_client")
	 * @Template("Pro3xInvoiceBundle:Customer:edit.html.twig")
	 */
	public function addAction()
	{
		return $this->saveCustomer(new Customer(), 'Unos kupca', 'Novi kupac je uspješno kreiran', 'client_add');
//		$form = $this->createForm(new CustomerType());
//		if($result = $this->saveForm($form, 'Novi kupac je uspješno kreiran')) return $result;
//
//		return array('form' => $form->createView(), 'title' => 'Unos novog kupca', 'cssClass' => 'pro3x_small_icon_client_add');
	}
	
	/**
	 * 
	 * @param Customer $client
	 * @param type $title
	 * @param type $msg
	 * @param type $icon
	 * @return type
	 */
	private function saveCustomer($client, $title, $msg, $icon)
	{
		$message = $client->getMessage();
		$warning = $client->getWarning();
		
		$customerType = new CustomerType();
		$details = $this->isInRole("user_details");
		$customerType->setShowUserDetails($details);
		
		$form = $this->createForm($customerType, $client);
		
		if($this->getRequest()->isMethod('post'))
		{
			$form->bind($this->getRequest());
			
//			if($form->isValid())
//			{
				$manager = $this->getDoctrine()->getEntityManager();
				$manager->persist($form->getData());
				
				if($client->getMessage() != $message)
				{
					$mNote = new \Pro3x\InvoiceBundle\Entity\Note();
					$mNote->setCustomer($client);
					$mNote->setContent($client->getMessage());
					$mNote->setCreatedBy($this->getUser());
					$mNote->setNoteType('message');

					$manager->persist($mNote);
				}
				
				if($client->getWarning() != $warning)
				{
					$wNote = new \Pro3x\InvoiceBundle\Entity\Note();
					$wNote->setCustomer($client);
					$wNote->setContent($client->getWarning());
					$wNote->setCreatedBy($this->getUser());
					$wNote->setNoteType('warning');

					$manager->persist($wNote);
				}
				
				$manager->flush();
				
				$this->addFlash('message', $msg);
				return $this->redirect($this->getBackUrl());
//			}
		}
		
		return $this->editParams($form, $title, $icon);
	}
	
	/**
	 * @Route("/edit/{id}", name="edit_client")
	 * @Template("Pro3xInvoiceBundle:Customer:edit.html.twig")
	 */
	public function editAction($id)
	{
		$client = $this->getCustomerRepository()->findOneById($id); /* @var $client Customer */
		$this->redirect404($client);
		
		return $this->saveCustomer($client, 'Izmjena kupca', 'Informacije o kupcu su uspješno izmijenjene', 'client_edit');
	}
	
	/**
	 * @Route("/delete/{id}", name="delete_client")
	 * @Template()
	 */
	public function deleteAction()
	{
		return $this->deleteEntity($this->getCustomerRepository(), 'Kupac je uspješno izbrisan');
	}
	
	/**
	 * @Route("/relation/add/{id}", name="customer_relations")
	 * @Security("has_role('ROLE_RELATIONS')")
	 * @Template()
	 */
	public function relationsAction($id)
	{
		$customer = $this->getCustomerRepository()->find($id);
		$relations = $this->getRelationTypeRepository()->findAll();
		
		return array('customer' => $customer, 'relations' => $relations);
	}
	
	/**
	 * @Route("/select/{owner}/{page}", name="select_customer", defaults={"page"=1})
	 * @Template("Pro3xInvoiceBundle:Customer:select.html.twig")
	 * @Security("has_role('ROLE_RELATIONS')")
	 */
	public function selectAction($owner, $page)
	{
		$owner = $this->getCustomerRepository()->find($owner);
		$clients = $this->getCustomerRepository()->findBy(array(), array('name' => 'ASC'), $this->getPageSize());
		$relation = $this->getRelationTypeRepository()->find($this->getParam('relation'));
		
		return array('owner' => $owner, 'relation' => $relation,'clients' => $clients, 'pagerParams' => array('owner' => $owner->getId(), 'relation' => $relation->getId()), 'search' => '', 'count' => $this->getCustomerRepository()->getCount(), 'page' => $page);
	}
	
	/**
	 * @Route("/selectBy/{owner}/{relation}/{page}", name="select_by_customer", defaults={"page"=1})
	 * @Template("Pro3xInvoiceBundle:Customer:select.html.twig")
	 * @Security("has_role('ROLE_RELATIONS')")
	 */
	public function selectByAction($owner, $relation, $page)
	{
		$search = $this->getParam('search', '');
		$offset = $this->getPageOffset($page);
		$pageSize = $this->getPageSize();
		
		$owner = $this->getCustomerRepository()->find($owner);
		$relation = $this->getRelationTypeRepository()->find($relation);
		$result = $this->getCustomerRepository()->findBySearchQuery($search, $offset, $pageSize);
		
		$pageCount = $this->getPageCount($result['count']);
		
		return array('owner' => $owner, 'relation' => $relation, 'clients' => $result['items'], 'search' => $search, 'pagerParams' => array('owner' => $owner->getId(), 'relation' => $relation->getId(), 'search' => $search), 'count' => $pageCount, 'page' => $page);
	}
	
	/**
	 * @Security("has_role('ROLE_RELATIONS')")
	 * @Route("/relations/add/{owner}/{related}/{relation}", name="add_customer_relation")
	 * @Template()
	 */
	public function addRelationAction($owner, $related, $relation)
	{
		$ownerCustomer = $this->getCustomerRepository()->find($owner);
		$relatedCustomer = $this->getCustomerRepository()->find($related);
		$relationType = $this->getRelationTypeRepository()->find($relation);
		
		$relation = new \Pro3x\InvoiceBundle\Entity\CustomerRelation();
		
		$relation->setOwner($ownerCustomer);
		$relation->setRelated($relatedCustomer);
		$relation->setRelationType($relationType);
		
		$manager = $this->getDoctrine()->getEntityManager();
		$manager->persist($relation);
		$manager->flush();

		$this->setMessage("Relacija je uspješno spremljena");
		return $this->goBack();
	}
	
	/**
	 * @Route("/relation/delete/{id}", name="delete_relation")
	 * @Template()
	 * @Security("has_role('ROLE_RELATIONS')")
	 */
	public function deleteRelationAction($id)
	{
		$relation = $this->getRelationsRepository()->find($id);
		
		$manager = $this->getDoctrine()->getEntityManager();
		$manager->remove($relation);
		$manager->flush();

		$this->setMessage("Relacija je uspješno izbrisana");
		
		return $this->goBack();
	}
	
	/**
	 * @Route("/notes/{id}", name="customer_notes")
	 * @Security("has_role('ROLE_NOTES')")
	 * @Template()
	 */
	public function notesAction($id)
	{
		$customer = $this->getCustomerRepository()->find($id);
		return array('customer' => $customer);
	}
	
	/**
	 * @Route("/notes/add/{id}", name="add_customer_note")
	 * @Security("has_role('ROLE_NOTES')")
	 * @Template("::edit.html.twig")
	 */
	public function addCustomerNoteAction($id)
	{
		$note = new \Pro3x\InvoiceBundle\Entity\Note();
		$note->setCreatedBy($this->getUser());
		
		$note->setCustomer($this->getCustomerRepository()->find($id));
		
		$handler = new \Pro3x\Online\AddHandler($this, $note);
		
		$handler->setTitle("Dodaj Bilješku")
				->setIcon("add_note")
				->setSuccessMessage("Bilješka je uspješno spremljena")
				->setFormType(new \Pro3x\InvoiceBundle\Form\NoteType());
		
		return $handler->execute();
	}
	
	/**
	 * @Route("/notes/delete/{id}", name="delete_customer_note")
	 * @Security("has_role('ROLE_NOTES')")
	 * @Template()
	 */
	public function deleteCustomerNoteAction()
	{
		return $this->deleteEntity($this->getNoteRepository(), 'Bilješka je uspješno izbrisana');
	}
	
	/**
	 * @Route("/notes/edit/{id}", name="edit_customer_note")
	 * @Template("::edit.html.twig")
	 * @Security("has_role('ROLE_NOTES')")
	 */
	public function editCustomerNoteAction($id)
	{
		$handler = new \Pro3x\Online\EditHandler($this, $id);

		$handler->setTitle("Izmjena Bilješke")
				->setIcon("edit_note")
				->setSuccessMessage("Bilješka je uspješno izmjenjena")
				->setRepository($this->getNoteRepository())
				->setFormType(new \Pro3x\InvoiceBundle\Form\NoteType());
		
		return $handler->execute();
	}
	
	/**
     * @Route("/{page}", name="clients", defaults={"page" = 1})
     * @Template()
     */
    public function indexAction($page)
    {
		if($this->isPost())
		{
			return $this->redirect($this->generateUrl('clients', array('qsearch' => $this->getParam('search'))));
		}
		else if($this->getParam('qsearch') != '')
		{
			$search = $this->getParam('qsearch', '');
			$offset = $this->getPageOffset($page);
			$pageSize = $this->getPageSize();
			
			$result = $this->getCustomerRepository()->findBySearchQuery($search, $offset, $pageSize);
			
			$pageCount = $this->getPageCount($result['count']);
			
			return array('clients' => $result['items'], 'icon' => 'client', 'search' => $search, 'pagerParams' => array('qsearch' => $search), 'count' => $pageCount, 'page' => $page);
		}
		else
		{
			$search = "";
			$clients = $this->getCustomerRepository()->findBy(array(), array('name' => 'ASC'), $this->getPageSize(), $this->getPageOffset($page));
			$count = $this->getPageCount($this->getCustomerRepository()->getCount());
			
			return array('clients' => $clients, 'icon' => 'client', 'placeholder' => 'Naziv ili OIB kupca', 'search' => $search, 'count' => $count, 'page' => $page);
		}        
    }
}

src/Pro3x/InvoiceBundle/Resources/views/Customer/mobile-customer-search.html.twig
<div class="visible-xs pro3x-invoice-index">
    {% for item in items %}
        <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ item.name }}</h3>
                </div>
                <table class="table">
                    <tbody>
                        {% if item.address %}
                        <tr>
                            <td class="active" style="width: 40%;">{{ 'Adresa'|trans }}</td>
                            <td>{{ item.address }}</td>
                        </tr>
                        {% endif %}
                        
                        {% if item.location %}
                        <tr>
                            <td class="active" style="width: 40%;">{{ 'Lokacija'|trans }}</td>
                            <td>{{ item.location }}</td>
                        </tr>
                        {% endif %}
                        {% if item.taxNumber %}
                        <tr>
                            <td class="active" style="width: 40%;">{{ 'OIB'|trans }}</td>
                            <td>{{ item.taxNumber }}</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div class="panel-footer">
                    <a class="btn btn-primary" href="{{ path(app.request.get('_route'), pagerParams|merge({(selectParam): attribute(item, selectColumn), 'back': app.request.get('back')})) }}">{{ 'Izaberi'|trans }}</a>
                </div>
            </div>
    {% endfor %}
    
    <div class="_row">
        <div class="col-xs-12" style="padding: 0px 0px 20px 0px;">
            <form method="post" autocomplete="off">
                <input type="hidden" name="back" value="{{ app.request.get('back') }}" />
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="{{ placeholder }}" name="query" value="{{ app.request.get('query') }}" />
                    <span class="input-group-btn"><input type="submit" class="btn btn-primary pro3x-medium-button" value="{{ 'Traži'|trans }}" /></span>
                </div>
            </form>
        </div>
    </div>
</div>    

src/Pro3x/InvoiceBundle/Resources/views/Customer/notes.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}<span class="pro3x_small_icon pro3x_small_icon_note"></span>{{ 'Bilješke'|trans }} | <a href="{{ path('edit_client', { 'id': customer.id, 'back': app.request.uri }) }}">{{ customer.descriptionFormated }}</a> {% endblock %}

{% block body %}
    <div class="grid_12">
	
	{% include '::message.html.twig' %}
	
	<table class="ui-widget-content ui-corner-all pro3x">
	    <thead>
		<tr>
		    <th class="ui-widget-header ui-corner-all">{{ 'Bilješka'|trans }}</th>
		</tr>
	    </thead>
	{% for note in customer.notes %}
	    <tr>
		<td class="pro3x_tools{% if note.noteType %} pro3x_note_{{ note.noteType }}{% endif %}">
		    <div>{{ note.created|date('d.m.Y - H:i') }}h | 
			<a href="{{ path('edit_customer_note', {'id': note.id, 'back': app.request.uri }) }}">izmjeni</a>
			<a class="pro3x_confirm" 
			    data-icon="pro3x_icon_client_delete" 
			    data-msg="{{ 'Jeste li sigurni da želite izbrisati bilješku?'|trans }}" 
			    href="{{ path('delete_customer_note', {'id': note.id, 'back': app.request.uri}) }}">{{ 'izbriši'|trans }}</a>
		    </div>
		    <div>{{ note.content }}</div>
		    {% if note.createdBy %}
		    <div class="pro3x_note_writer">Napisao: {{ note.createdBy.displayName }}</div>
		    {% endif %}
		</td>
	    </tr>
	{% else %}
	    <tr>
		<td class="pro3x_no_data" colspan="100">{{ 'Nema rezultata'|trans }}</td>
	    </tr>
	{% endfor %}
	</table>
    </div>

    <div class="grid_8">
	<div class="pro3x_table_buttons" style="margin-top: 0.6em;">
	    <input type="button" data-href="{{ path('add_customer_note', { 'id': customer.id, 'back': app.request.uri}) }}" class="button link" value="{{ 'Dodaj'|trans }}" />
	    <input type="button" data-href="{{ app.request.get('back') }}" class="button link" value="{{ 'Odustani'|trans }}" />
	</div>
    </div>

    <div class="pro3x_dialog" title="{{ 'Upozorenje!'|trans }}"></div>

{% endblock %}

{% block javascripts %}{% endblock %}

src/Pro3x/InvoiceBundle/Resources/views/Customer/relations.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}<span class="pro3x_small_icon pro3x_small_icon_client"></span>{{ 'Relacije'|trans }} | <a href="{{ path('edit_client', { 'id': customer.id, 'back': app.request.uri }) }}">{{ customer.descriptionFormated }}</a> {% endblock %}

{% block body %}
    <div class="grid_12">
	
	{% include '::message.html.twig' %}
	
	<table class="ui-widget-content ui-corner-all pro3x">
	    <thead>
		<tr>
		    <th class="ui-widget-header ui-corner-all">{{ 'Informacije o kupcu'|trans }}</th>
		    <th class="ui-widget-header ui-corner-all">{{ 'Relacija'|trans }}</th>
		    <th class="ui-widget-header ui-corner-all" style="width: 300px;">{{ 'Kontakt informacije'|trans }}</th>
		    <th class="ui-widget-header ui-corner-all" style="width: 200px;">{{ 'Alati'|trans }}</th>
		</tr>
	    </thead>
	{% for relation in customer.relations %}
	{% set client = relation.related %}
	    <tr>
		<td>
		    {% if client.taxNumber %}<div>OIB: {{ client.taxNumber }}{% if client.birthday %} | {{ client.birthday|date('d.m.Y') }}{% endif %}</div>{% endif %}
		    <div>{{ client.description|join(', ') }}</div>
		</td>
		<td>{{ relation.relationType.description }}</td>
		<td>
		    <div>{{ client.email }}</div>
		    <div>{{ client.phones|join(', ') }}</div>
		</td>
		<td class="pro3x_tools">
		    <a class="pro3x_confirm" 
		       data-icon="pro3x_icon_client_delete" 
		       data-msg="{{ 'Jeste li sigurni da želite izbrisati relaciju <b>%owner%</b> sa <b>%name%</b>?'|trans({ '%name%': client.name, '%owner%': customer.name }) }}" 
		       href="{{ path('delete_relation', {'id': relation.id, 'back': app.request.uri}) }}">{{ 'izbriši'|trans }}</a>
		</td>
	    </tr>
	{% else %}
	    <tr>
		<td class="pro3x_no_data" colspan="100">{{ 'Nema rezultata'|trans }}</td>
	    </tr>
	{% endfor %}
	</table>
    </div>

    <div class="grid_8">
	<div class="pro3x_table_buttons" style="margin-top: 0.6em;">
	    <form class="pro3x pro3x_separate_right" action="{{ path('select_customer', {'owner': app.request.get('id')}) }}" method="GET">
		<input type="hidden" name="back" value="{{ app.request.uri }}" />
		<select name="relation" class="pro3x">
		    {% for relation in relations %}
			<option value="{{ relation.id }}">{{ relation.description }}</option>
		    {% endfor %}
		</select>
		<input type="submit" class="button" value="{{ 'Dodaj'|trans }}" />
	    </form>
	    <input type="button" data-href="{{ app.request.get('back') }}" class="button link" value="{{ 'Odustani'|trans }}" />
	</div>
    </div>

    <div class="pro3x_dialog" title="{{ 'Upozorenje!'|trans }}"></div>

{% endblock %}

{% block javascripts %}{% endblock %}

src/Pro3x/InvoiceBundle/Resources/views/Customer/select.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}<span class="pro3x_small_icon pro3x_small_icon_client"></span>{{ 'Izbor | %relation%'|title|trans({'%relation%': relation.description}) }}
| <a href="{{ path('edit_client', {'id': owner.id, 'back': app.request.uri}) }}">{{ owner.descriptionFormated }}</a>
{% endblock %}

{% block body %}
    <div class="grid_12">
	
	{% include '::message.html.twig' %}
	
	<table class="ui-widget-content ui-corner-all pro3x">
	    <thead>
		<tr>
		    <th class="ui-widget-header ui-corner-all">{{ 'Informacije o kupcu'|trans }}</th>
		    <th class="ui-widget-header ui-corner-all" style="width: 300px;">{{ 'Kontakt informacije'|trans }}</th>
		    <th class="ui-widget-header ui-corner-all" style="width: 200px;">{{ 'Alati'|trans }}</th>
		</tr>
	    </thead>
	{% for client in clients %}
	    <tr>
		<td>
		    {% if client.taxNumber %}<div>OIB: {{ client.taxNumber }}{% if client.birthday %} | {{ client.birthday|date('d.m.Y') }}{% endif %}</div>{% endif %}
		    <div>{{ client.description|join(', ') }}</div>
		</td>
		<td>
		    <div>{{ client.email }}</div>
		    <div>{{ client.phones|join(', ') }}</div>
		</td>
		<td class="pro3x_tools" style="width: 200px;">
		    <a href="{{ path('add_customer_relation', {'owner': owner.id, 'related': client.id, 'relation': app.request.get('relation'), 'back': app.request.get('back')}) }}">odaberi</a>
		</td>
	    </tr>
	{% else %}
	    <tr>
		<td class="pro3x_no_data" colspan="100">{{ 'Nema rezultata'|trans }}</td>
	    </tr>
	{% endfor %}
	</table>
    </div>

    <div class="grid_8">
	<div class="pro3x_table_buttons" style="margin-top: 0.6em;">
	    <form action="{{ path('select_by_customer', {'owner': owner.id, 'relation': relation.id, 'back': app.request.get('back')}) }}" class="pro3x pro3x_separate_right" method="POST">
		<input class="pro3x" type="text" name="search" value="{{ search }}" />
		<input class="button" type="submit" name="action" value="Traži" />
	    </form>
	    <input type="button" data-href="{{ path('add_client', {'back': app.request.uri}) }}" class="button link" value="{{ 'Dodaj'|trans }}" />
	    <input type="button" data-href="{{ app.request.get('back') }}" class="button link" value="{{ 'Odustani'|trans }}" />
	</div>
    </div>

    {% include '::pager.html.twig' with {'count': count, 'page': page} %}

    <div class="pro3x_dialog" title="{{ 'Upozorenje!'|trans }}"></div>

{% endblock %}

{% block javascripts %}{% endblock %}