src/Pro3x/SecurityBundle/Entity/User.php
<?php

namespace Pro3x\SecurityBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use Pro3x\SecurityBundle\Entity\Group;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\ManyToOne;

/**
 * Pro3x\SecurityBundle\Entity\User
 *
 * @ORM\Table(name="pro3x_users")
 * @ORM\Entity
 */
class User implements UserInterface, EquatableInterface, AdvancedUserInterface
{
	function __construct()
	{
		$this->isActive = true;
		$this->salt = md5(uniqid(null, true));
		$this->groups = new ArrayCollection();
		$this->invoices = new ArrayCollection();
	}

	
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
	
	/**
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $displayName;
	
	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $position;

//	/**
//	 * @ManyToOne(targetEntity="Pro3x\InvoiceBundle\Entity\Position", inversedBy="users", fetch="EAGER")
//	  */
//	protected $position;

	/**
	 * @OneToMany(targetEntity="Pro3x\InvoiceBundle\Entity\Invoice", mappedBy="user")
	  */
	protected $invoices;
	
	/**
	 * @OneToMany(targetEntity="Pro3x\InvoiceBundle\Entity\Note", mappedBy="createdBy")
	  */
	private $notes;
	
	public function getPosition()
	{
		return $this->position;
	}

	public function setPosition($position)
	{
		$this->position = $position;
	}

	public function getInvoices()
	{
		return $this->invoices;
	}

	public function setInvoices($invoices)
	{
		$this->invoices = $invoices;
	}

	public function getDisplayName()
	{
		if($this->displayName)
			return $this->displayName;
		else
			return $this->username;
	}

	public function setDisplayName($displayName)
	{
		$this->displayName = $displayName;
	}

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

	public function eraseCredentials()
	{
		
	}
	
	/**
	 *
	 * @var ArrayCollection
	 * @ORM\ManyToMany(targetEntity="Group", inversedBy="users")
	 * @ORM\JoinTable(name="pro3x_users_groups")
	 */
	protected $groups;
	
	/**
	 * 
	 * @return ArrayCollection
	 */
	public function getGroups()
	{
		return $this->groups;
	}

	/**
	 *
	 * @var string
	 * @ORM\Column(type="string")
	 */
	protected $password;
	
	public function getPassword()
	{
		return $this->password;
	}

	public function setPassword($password)
	{
		$this->password = $password;
	}
	
	public function getRoles()
	{
            $roles = array();
            
            foreach ($this->getGroups() as $group) {
                $roles[] = $group->getRole();
            }

            return $roles;
	}

	/**
	 *
	 * @var string
	 * @ORM\Column(type="string")
	 */
	protected $salt;
	
	public function getSalt()
	{
		return $this->salt;
	}

	/**
	 *
	 * @var string
	 * @ORM\Column(type="string", unique=true)
	 */
	protected $username;
	
	public function getUsername()
	{
		return $this->username;
	}
	
	public function setUsername($username)
	{
		$this->username = $username;
	}
	
	/**
	 *
	 * @var string
	 * @ORM\Column(type="string", unique=true)
	 */
	protected $email;

	public function getEmail()
	{
		return $this->email;
	}
	
	public function setEmail($email)
	{
		$this->email = $email;
	}
	
	/**
	 *
	 * @var boolean
	 * @ORM\Column(type="boolean", name="is_active")
	 */
	protected $isActive;
	
	public function isActive()
	{
		return $this->isActive;
	}

	public function setActive($isActive)
	{
		$this->isActive = $isActive;
	}

	/**
	 *
	 * @var string
	 * @ORM\Column(type="string", nullable=true)
	 */
	protected $oib;
	
	public function getOib()
	{
		return $this->oib;
	}

	public function setOib($oib)
	{
		$this->oib = $oib;
	}

	public function isEqualTo(UserInterface $user)
	{
		return $this->username === $user->getUsername();
	}

	public function isAccountNonExpired()
	{
		return true;
	}

	public function isAccountNonLocked()
	{
		return true;
	}

	public function isCredentialsNonExpired()
	{
		return true;
	}

	public function isEnabled()
	{
		return $this->isActive;
	}
}

src/Pro3x/SecurityBundle/Resources/views/Security/list.html.twig
{% extends '::base.html.twig' %}

{% block page_title %}Korisnici{% endblock %}

{% block body %}
    <div class="grid_12">
	
	{% include '::message.html.twig' %}
	
	<table class="ui-widget-content ui-corner-all pro3x">
	    <thead>
		<tr>
		    {% if is_granted('ROLE_OIB') %}
			<th class="ui-widget-header ui-corner-all">Oib</th>
		    {% endif %}
		    <th class="ui-widget-header ui-corner-all">Korisničko ime</th>
		    <th class="ui-widget-header ui-corner-all">Elektronička pošta</th>
		    <th class="ui-widget-header ui-corner-all">Aktivan</th>
		    <th class="ui-widget-header ui-corner-all">Omogućen</th>
		    <th class="ui-widget-header ui-corner-all">Alati</th>
		</tr>
	    </thead>
	{% for user in users %}
	    <tr>
		{% if is_granted('ROLE_OIB') %}
		    <td>{{ user.oib }}</td>
		{% endif %}
		<td>{{ user.username }}</td>
		<td>{{ user.email }}</td>
		<td><span class="ui-icon {{ user.active?'ui-icon-check':'ui-icon-closethick' }}"></span></td>
		<td><span class="ui-icon {{ user.enabled?'ui-icon-check':'ui-icon-closethick' }}"></span></td>
		<td class="pro3x_tools">
		    <a href="">edit</a>
		    <a class="pro3x_confirm" data-msg="Jeste li sigurni da želite izbrisati korisnika <b>{{ user.username }}</b>?" href="{{ path('delete_user', {'id': user.id, 'back': app.request.uri}) }}">delete</a>
		</td>
	    </tr>
	{% else %}
	    <tr>
		<td class="pro3x_no_data" colspan="100">Nema rezultata</td>
	    </tr>
	{% endfor %}
	</table>
    </div>

    {% include '::pager.html.twig' with {'count': count, 'page': page} %}

    <div class="pro3x_dialog" title="Upozorenje!"></div>

{% endblock %}

{% block javascripts %}

    

{% endblock %}